'use client';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowLeft, ArrowRight, X } from 'lucide-react';
import { site, appointmentUrl } from '@/data/site';
import { EssenceChapter } from './essence-chapter';
import { AuthorChapter } from './author-chapter';
import { ExperienceStatement } from './experience-statement';

const pad = (n:number) => String(n+1).padStart(2,'0');
function Tag({children}:{children:React.ReactNode}){return <p className="chapter-tag">{children}</p>}
function ContactLink({children='Agendar consulta'}:{children?:React.ReactNode}){return <a className="chapter-link" href={appointmentUrl} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={22}/></a>}

export function Chapters(){return <>
 <EssenceChapter/><Procedures/>{site.results.enabled&&<ResultGallery/>}<AuthorChapter/><ExperienceStatement/><RealTestimonials/>
 <section id="contato" className="closing-chapter" aria-labelledby="contact-title"><div className="section-topline"><Tag>06 — VAMOS CONVERSAR</Tag><span/><p>RECIFE & SURUBIM</p></div><div className="closing-composition"><div><h2 id="contact-title" data-reveal>O próximo<br/>olhar é <em>seu.</em></h2><p data-reveal>Um primeiro encontro para falar sobre você.<br/>E descobrir, juntas, as possibilidades.</p><ContactLink>Agendar minha avaliação</ContactLink></div><a className="closing-orbit" href={appointmentUrl} target="_blank" rel="noreferrer" aria-label="Conversar com a Dra. Paula Brito no WhatsApp"><ArrowUpRight strokeWidth={.7}/><span>VAMOS COMEÇAR?</span></a></div><div className="contact-social"><p>{site.address}</p><a href={site.instagram} target="_blank" rel="noreferrer">{site.instagramHandle} <ArrowUpRight size={17}/></a></div></section>
 </>}

function ResultGallery(){const track=useRef<HTMLDivElement>(null);const scroll=(direction:number)=>{const el=track.current;if(!el)return;const card=el.firstElementChild as HTMLElement|null;el.scrollBy({left:direction*((card?.offsetWidth||400)+28),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};const[active,setActive]=useState<number|null>(null);const[compare,setCompare]=useState(false);const[value,setValue]=useState(50);const dialog=useRef<HTMLDialogElement>(null);const opener=useRef<HTMLButtonElement|null>(null);const items=site.results.items;const item=active===null?null:items[active];
 useEffect(()=>{if(active!==null){if(!dialog.current?.open)dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[active]);
 const close=()=>{setActive(null);opener.current?.focus()};const move=(delta:number)=>{setActive(i=>i===null?0:(i+delta+items.length)%items.length);setValue(50);setCompare(false)};
 return <section id="resultados" className="gallery-chapter"><div className="gallery-top"><Tag>03 — RESULTADOS</Tag><span>{String(items.length).padStart(2,'0')} REGISTROS REAIS</span></div><div className="gallery-heading" data-reveal><h2>A sutileza<br/><em>faz a diferença.</em></h2><div className="gallery-intro"><p>Histórias e traços reais.<br/>Um olhar mais próximo dos detalhes.</p><div className="gallery-controls"><button aria-label="Ver resultados anteriores" onClick={()=>scroll(-1)}><ArrowLeft size={21}/></button><button aria-label="Ver próximos resultados" onClick={()=>scroll(1)}><ArrowRight size={21}/></button><span>EXPLORE OS REGISTROS</span></div></div></div><div ref={track} className="gallery-grid" tabIndex={0} aria-label="Galeria de resultados. Use as setas para navegar." onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'){e.preventDefault();scroll(1)}if(e.key==='ArrowLeft'){e.preventDefault();scroll(-1)}}}>{items.map((r,i)=><figure className={`gallery-item gallery-item-${i}`} key={r.image} data-reveal><button onClick={e=>{opener.current=e.currentTarget;setCompare(false);setValue(50);setActive(i)}} aria-label={`Ampliar resultado ${pad(i)}: ${r.label}`}><div className="gallery-photo"><Image src={r.image} alt={r.alt} fill sizes="(max-width:700px) 83vw, 36vw"/></div><span className="gallery-open"><ArrowUpRight size={23}/></span></button><figcaption><span><small>{pad(i)} /</small> {r.label}</span><span>{r.orientation==='single'?'REGISTRO':'ANTES & DEPOIS'}</span></figcaption></figure>)}</div><div className="gallery-end"><p>Fotografias compartilhadas pela Dra. {site.name}.<br/>Resultados individuais. Cada pessoa tem características próprias.</p><ContactLink>O seu primeiro passo</ContactLink></div>
 <dialog ref={dialog} className="result-dialog" aria-labelledby="viewer-title" onCancel={close} onClose={()=>setActive(null)} onKeyDown={e=>{if((e.target as HTMLElement).tagName==='INPUT')return;if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}}>{item&&<><div className="viewer-top"><div><Tag>Um olhar mais próximo</Tag><h3 id="viewer-title">{item.label}</h3></div><button className="viewer-icon" onClick={close} aria-label="Fechar resultado"><X/></button></div><div className="viewer-stage">{compare&&item.orientation!=='single'?<div className={`comparison ${item.orientation==='vertical'?'vertical':''}`} style={{aspectRatio:item.comparisonRatio}}><div className="compare-half after" style={{backgroundImage:`url(${item.image})`,backgroundSize:item.orientation==='vertical'?`100% ${100/(1-item.beforeShare)}%`:`${100/(1-item.beforeShare)}% 100%`}}/><div className="compare-half before" style={{backgroundImage:`url(${item.image})`,backgroundSize:item.orientation==='vertical'?`100% ${100/item.beforeShare}%`:`${100/item.beforeShare}% 100%`,clipPath:`inset(0 ${100-value}% 0 0)`}}/><div className="comparison-line" style={{left:`${value}%`}}><span>↔</span></div><span className="compare-label left">Antes</span><span className="compare-label right">Depois</span></div>:<Image src={item.image} alt={item.alt} fill sizes="90vw"/>}</div>{compare&&<label className="viewer-range">Deslize para comparar<input type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)} aria-label="Proporção entre antes e depois"/></label>}<div className="viewer-bottom"><button className="viewer-icon" aria-label="Resultado anterior" onClick={()=>move(-1)}><ArrowLeft/></button><span aria-live="polite">{pad(active!)} / {String(items.length).padStart(2,'0')}</span>{item.orientation!=='single'&&<button className="viewer-mode" aria-pressed={compare} onClick={()=>{setCompare(!compare);setValue(50)}}>{compare?'Ver foto original':'Comparar antes e depois'}</button>}<button className="viewer-icon" aria-label="Próximo resultado" onClick={()=>move(1)}><ArrowRight/></button></div>{compare&&<p className="viewer-note">Recortes do registro original. Enquadramentos podem variar.</p>}</>}</dialog>
 </section>
}
function RealTestimonials(){const[index,setIndex]=useState(0);if(!site.testimonials.length)return null;return <section className="voices-chapter"><Tag>Palavras de quem viveu</Tag><blockquote>“{site.testimonials[index].quote}”</blockquote><p>{site.testimonials[index].name}</p><button className="chapter-link" onClick={()=>setIndex((index+1)%site.testimonials.length)}>Próximo relato<ArrowRight/></button></section>}


function Procedures(){const[selected,setSelected]=useState(0);return <section className="procedures-chapter" id="cuidados" aria-labelledby="procedures-title"><div className="procedures-top"><Tag>02 — HARMONIZAÇÃO FACIAL</Tag><h2 id="procedures-title" data-reveal>Detalhes em equilíbrio.<br/><em>Você, por inteiro.</em></h2></div><div className="procedures-composition"><figure className="procedure-visual"><Image key={selected} src={site.procedures[selected].image} alt={site.procedures[selected].name==='Rejuvenescimento facial'?'Dra. Paula Brito em atendimento':'Registro clínico da Dra. Paula Brito: '+site.procedures[selected].name} fill sizes="(max-width:700px) 88vw, 40vw"/><figcaption><span>UM OLHAR PARA CADA DETALHE</span><span>0{selected+1}</span></figcaption></figure><div className="procedures-list"><p>Cada rosto pede um planejamento. Conheça algumas possibilidades de cuidado.</p>{site.procedures.map((procedure,i)=><details name="care" key={procedure.name} open={i===0} onToggle={e=>{if(e.currentTarget.open)setSelected(i)}}><summary><span>{pad(i)}</span><h3>{procedure.name}</h3><span className="procedure-plus" aria-hidden="true">+</span></summary><div className="procedure-description"><p>{procedure.description}</p><a href={appointmentUrl} target="_blank" rel="noreferrer">Conversar sobre este cuidado <ArrowUpRight size={18}/></a></div></details>)}<p className="procedure-note">A indicação de qualquer procedimento depende de avaliação individual.</p></div></div></section>}
